apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 469.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: b29b5ea5-b584-49a2-ad31-4943e962452f
    serving.knative.dev/creator: cristinarlr@gmail.com
    serving.knative.dev/lastModifier: cristinarlr@gmail.com
  creationTimestamp: '2024-04-15T15:59:23.817060Z'
  generation: 1
  labels:
    cloud.googleapis.com/location: us-central1
  name: wp-run-h3
  namespace: '1051691346478'
  resourceVersion: AAYWJLelEPw
  selfLink: /apis/serving.knative.dev/v1/namespaces/1051691346478/services/wp-run-h3
  uid: aac5aa27-aeb2-429a-9507-003b78d57adf
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 469.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: spxrozjjdh
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/desafio-altostratus/desafio-altostratus-wp-offline
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 1051691346478-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://wp-run-h3-3mcij6mdla-uc.a.run.app
  conditions:
  - lastTransitionTime: '2024-04-15T16:00:15.945980Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2024-04-15T15:59:23.989707Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2024-04-15T16:00:15.910595Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: wp-run-h3-00001-4cz
  latestReadyRevisionName: wp-run-h3-00001-4cz
  observedGeneration: 1
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: wp-run-h3-00001-4cz
  url: https://wp-run-h3-3mcij6mdla-uc.a.run.app
